find_package(pugixml CONFIG QUIET)
if(TARGET pugixml::pugixml)
    if(NOT TARGET PugiXML::PugiXML)
        add_library(PugiXML::PugiXML INTERFACE IMPORTED)
        set_target_properties(PugiXML::PugiXML PROPERTIES INTERFACE_LINK_LIBRARIES pugixml::pugixml)
    endif()
    set(PugiXML_FOUND TRUE)
    return()
endif()
find_path(PUGIXML_INCLUDE_DIR NAMES pugixml.hpp)
find_library(PUGIXML_LIBRARY NAMES pugixml)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PugiXML REQUIRED_VARS PUGIXML_INCLUDE_DIR PUGIXML_LIBRARY)
if(PugiXML_FOUND AND NOT TARGET PugiXML::PugiXML)
    add_library(PugiXML::PugiXML UNKNOWN IMPORTED)
    set_target_properties(PugiXML::PugiXML PROPERTIES IMPORTED_LOCATION "${PUGIXML_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${PUGIXML_INCLUDE_DIR}")
endif()
mark_as_advanced(PUGIXML_INCLUDE_DIR PUGIXML_LIBRARY)
