find_package(unofficial-luajit CONFIG QUIET)
if(TARGET unofficial::luajit::luajit)
    add_library(LuaJIT::LuaJIT INTERFACE IMPORTED)
    set_target_properties(LuaJIT::LuaJIT PROPERTIES INTERFACE_LINK_LIBRARIES unofficial::luajit::luajit)
    set(LuaJIT_FOUND TRUE)
    return()
endif()
find_path(LUAJIT_INCLUDE_DIR NAMES luajit.h HINTS ENV LUA_DIR
    PATH_SUFFIXES include/luajit-2.1 include/luajit-2.0 include/luajit include luajit-2.1 luajit-2.0)
find_library(LUAJIT_LIBRARY NAMES luajit-5.1 luajit lua51
    HINTS ENV LUA_DIR PATH_SUFFIXES lib lib64)
if(VCPKG_INSTALLED_DIR AND VCPKG_TARGET_TRIPLET)
    find_library(LUAJIT_DEBUG_LIBRARY NAMES luajit-5.1 luajit lua51
        PATHS "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib" NO_DEFAULT_PATH)
endif()
if(LUAJIT_INCLUDE_DIR)
    file(STRINGS "${LUAJIT_INCLUDE_DIR}/luajit.h" _luajit_version
        REGEX "^#define[ \t]+LUAJIT_VERSION[ \t]+")
    string(REGEX REPLACE [[.*LuaJIT ([^"]+).*]] "\\1" LUAJIT_VERSION_STRING "${_luajit_version}")
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LuaJIT REQUIRED_VARS LUAJIT_INCLUDE_DIR LUAJIT_LIBRARY
    VERSION_VAR LUAJIT_VERSION_STRING)
if(LuaJIT_FOUND AND NOT TARGET LuaJIT::LuaJIT)
    add_library(LuaJIT::LuaJIT UNKNOWN IMPORTED)
    set_target_properties(LuaJIT::LuaJIT PROPERTIES IMPORTED_LOCATION "${LUAJIT_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${LUAJIT_INCLUDE_DIR}")
    if(LUAJIT_DEBUG_LIBRARY)
        set_target_properties(LuaJIT::LuaJIT PROPERTIES IMPORTED_LOCATION_DEBUG "${LUAJIT_DEBUG_LIBRARY}")
    endif()
    if(UNIX)
        set_property(TARGET LuaJIT::LuaJIT APPEND PROPERTY INTERFACE_LINK_LIBRARIES "${CMAKE_DL_LIBS};m")
    endif()
endif()
mark_as_advanced(LUAJIT_INCLUDE_DIR LUAJIT_LIBRARY LUAJIT_DEBUG_LIBRARY)
