# Exported targets carry the connector's TLS and static link dependencies.
find_package(unofficial-libmariadb CONFIG QUIET)
if(TARGET unofficial::libmariadb)
    add_library(MySQL::Client INTERFACE IMPORTED)
    set_target_properties(MySQL::Client PROPERTIES INTERFACE_LINK_LIBRARIES unofficial::libmariadb)
    set(MySQL_FOUND TRUE)
    return()
endif()
find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
    pkg_search_module(TFS_MYSQL QUIET IMPORTED_TARGET libmariadb mariadb mysqlclient)
    if(TFS_MYSQL_FOUND)
        add_library(MySQL::Client INTERFACE IMPORTED)
        set_target_properties(MySQL::Client PROPERTIES INTERFACE_LINK_LIBRARIES PkgConfig::TFS_MYSQL)
        set(MySQL_FOUND TRUE)
        return()
    endif()
endif()
# Manual installations can set MYSQL_INCLUDE_DIR and MYSQL_LIBRARY.
find_path(MYSQL_INCLUDE_DIR NAMES mysql.h HINTS ENV MYSQL_DIR
    PATH_SUFFIXES include include/mysql include/mariadb mysql mariadb)
find_library(MYSQL_LIBRARY NAMES mariadb libmariadb mysqlclient libmysql
    HINTS ENV MYSQL_DIR PATH_SUFFIXES lib lib64)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MySQL REQUIRED_VARS MYSQL_INCLUDE_DIR MYSQL_LIBRARY)
if(MySQL_FOUND AND NOT TARGET MySQL::Client)
    add_library(MySQL::Client UNKNOWN IMPORTED)
    set_target_properties(MySQL::Client PROPERTIES IMPORTED_LOCATION "${MYSQL_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${MYSQL_INCLUDE_DIR}")
endif()
mark_as_advanced(MYSQL_INCLUDE_DIR MYSQL_LIBRARY)
